spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    aws:
      region:
        static: ap-southeast-1

aws:
  region: ap-southeast-1
  s3:
    bucket: managementproduct

logging:
  level:
    com.example.demo: INFO
