server:
  port: 8081
spring:
  datasource:
#        url: jdbc:postgresql://localhost:5432/postgres
#        username: postgres
#        password: 123456
#        driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    aws:
      region:
        static: ap-southeast-1
  liquibase:
    change-log: classpath:/migration/db.changelog-master.yaml
    enabled: true
    default-schema: product_liquibase
aws:
  region: ap-southeast-1
  s3:
    bucket: managementproduct

#logging:
#  level:
#    com.example.demo: INFO
#    schemaName: product_liquibase
