databaseChangeLog:
  - changeSet:
      id: product-1
      author: BE PRODUCT
      changes:
        - createTable:
            tableName: product
            schemaName: product_liquibase
            columns:
              - column:
                  name: product_id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
              - column:
                  name: product_code
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: description
                  type: TEXT
              - column:
                  name: price
                  type: DECIMAL(15,2)
                  constraints:
                    nullable: false
              - column:
                  name: quantity
                  type: INT
                  constraints:
                    nullable: false
              - column:
                  name: unit
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: status
                  type: VARCHAR(50)
              - column:
                  name: created_at
                  type: TIMESTAMP
              - column:
                  name: updated_at
                  type: TIMESTAMP
              - column:
                  name: barcode
                  type: VARCHAR(100)
              - column:
                  name: min_stock
                  type: INT
                  constraints:
                    nullable: false
              - column:
                  name: category_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: warehouse_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: supplier_id
                  type: BIGINT
                  constraints:
                    nullable: false
        - addForeignKeyConstraint:
            baseTableName: product
            baseColumnNames: category_id
            constraintName: fk_product_category
            referencedTableName: category
            referencedColumnNames: category_id
            baseTableSchemaName: product_liquibase
            referencedTableSchemaName: product_liquibase
        - addForeignKeyConstraint:
            baseTableName: product
            baseColumnNames: warehouse_id
            constraintName: fk_product_warehouse
            referencedTableName: warehouse
            referencedColumnNames: warehouse_id
            baseTableSchemaName: product_liquibase
            referencedTableSchemaName: product_liquibase
        - addForeignKeyConstraint:
            baseTableName: product
            baseColumnNames: supplier_id
            constraintName: fk_product_supplier
            referencedTableName: supplier
            referencedColumnNames: supplier_id
            baseTableSchemaName: product_liquibase
            referencedTableSchemaName: product_liquibase